version: '2'

services:
  ctfd:
    build: .
    user: root
    restart: always
    ports:
      - "8000:8000"
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://root:ctfd@db/ctfd
      - REDIS_URL=redis://cache:6379
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
      - .:/opt/CTFd:ro
    depends_on:
      - db
    networks:
        default:
        internal:

  db:
    image: mariadb:10.4
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ctfd
      - MYSQL_USER=ctfd
      - MYSQL_PASSWORD=ctfd
      - MYSQL_DATABASE=ctfd
    volumes:
      - .data/mysql:/var/lib/mysql
    networks:
        internal:
    # This command is required to set important mariadb defaults
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

  cache:
    image: redis:4
    restart: always
    volumes:
    - .data/redis:/data
    networks:
        internal:

  web01:
    build: ./challenges/web01/web/
    restart: always
    ports:
      - "10001:80"
    volumes:
      - ./challenges/web01/web/pages:/usr/local/apache2/htdocs
    depends_on:
      - web01-db
    networks:
      default:
      web01: 

  web01-db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=sample_db
    volumes:
      - ./challenges/web01/db/initdb.d:/docker-entrypoint-initdb.d
      - ./challenges/web01/db/conf.d:/etc/mysql/conf.d
    networks:
      web01:

  web02:
    build: ./challenges/web02/web/
    restart: always
    ports:
      - "10002:80"
    volumes:
      - ./challenges/web02/web/pages:/usr/local/apache2/htdocs
    depends_on:
      - web02-db
    networks:
      default:
      web02: 

  web02-db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=sample_db
    volumes:
      - ./challenges/web02/db/initdb.d:/docker-entrypoint-initdb.d
      - ./challenges/web02/db/conf.d:/etc/mysql/conf.d
    networks:
      web02:

  web03:
    build: ./challenges/web03/web/
    environment: 
      - FLAG=ctfgate{51mpl3_
    restart: always
    ports:
      - "10003:80"

  web03-cr:
    build: ./challenges/web03/crawler/
    environment:
      - APP_URL_BASE=web03
      - FLAG=x55_15_fun!}
    volumes:
      - ./challenges/web03/crawler:/app
    depends_on:
      - web03
    cap_add:
      - SYS_ADMIN

  web04:
    build: ./challenges/web04/web/
    restart: always
    ports:
      - "10004:80"
    volumes:
      - ./challenges/web04/web/pages:/usr/local/apache2/htdocs
  
  web05:
    build: ./challenges/web05/web/
    restart: always
    ports:
      - "10005:80"
    volumes:
      - ./challenges/web05/web/pages:/usr/local/apache2/htdocs

  web06:
    build: ./challenges/web06/web/
    restart: always
    ports:
      - "10006:80"
    volumes:
      - ./challenges/web06/web/pages:/usr/local/apache2/htdocs

  web07:
    build: ./challenges/web07/web/
    restart: always
    ports:
      - "10007:80"

  web08:
    build: ./challenges/web08/web/
    restart: always
    ports:
      - "10008:80"
    volumes:
      - ./challenges/web08/web/pages:/usr/local/apache2/htdocs

  web09:
    build: ./challenges/web09/web/
    restart: always
    ports:
      - "10009:80"
    volumes:
      - ./challenges/web09/web/pages:/usr/local/apache2/htdocs
    depends_on:
      - web09-db
    networks:
      default:
      web09: 

  web09-db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=sample_db
    volumes:
      - ./challenges/web09/db/initdb.d:/docker-entrypoint-initdb.d
      - ./challenges/web09/db/conf.d:/etc/mysql/conf.d
    networks:
      web09:

  web10:
    build: ./challenges/web10/web/
    restart: always
    ports:
      - "10010:80"
    volumes:
      - ./challenges/web10/web/pages:/usr/local/apache2/htdocs

  web11:
    build: ./challenges/web11/web/
    restart: always
    ports:
      - "10011:80"

  web11-cr:
    build: ./challenges/web11/crawler/
    environment:
      - APP_URL_BASE=web11
      - PASS=d027ac1d8b34c6a0c62f52ef1c84e2d5
    volumes:
      - ./challenges/web11/crawler:/app
    depends_on:
      - web11
    cap_add:
      - SYS_ADMIN

  web12:
    build: ./challenges/web12/web/
    restart: always
    ports:
      - "10012:80"

  web12-cr:
    build: ./challenges/web12/crawler/
    environment:
      - APP_URL_BASE=web12
      - FLAG=ctfgate{d0m_b453d_15_d1ff1cul7_f0r_m3}
    volumes:
      - ./challenges/web12/crawler:/app
    depends_on:
      - web12
    cap_add:
      - SYS_ADMIN

networks:
    default:
    web01:
        internal: true
    web02:
        internal: true
    web09:
        internal: true
    internal:
        internal: true
