version: '2'

services:
  ctfd:
    build: .
    user: root
    restart: always
    ports:
      - "8000:8000"
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://root:ctfd@db/ctfd
      - REDIS_URL=redis://cache:6379
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
      - .:/opt/CTFd:ro
    depends_on:
      - db
    networks:
        default:
        internal:

  db:
    image: mariadb:10.4
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ctfd
      - MYSQL_USER=ctfd
      - MYSQL_PASSWORD=ctfd
      - MYSQL_DATABASE=ctfd
    volumes:
      - .data/mysql:/var/lib/mysql
    networks:
        internal:
    # This command is required to set important mariadb defaults
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

  cache:
    image: redis:4
    restart: always
    volumes:
    - .data/redis:/data
    networks:
        internal:

  web01:
    build: ./challenges/web01/web/
    restart: always
    ports:
      - "10001:80"
    volumes:
      - ./challenges/web01/web/pages:/var/www/html
    depends_on:
      - web01-db
    networks:
      default:
      web01: 

  web01-db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=sample_db
    volumes:
      - ./challenges/web01/db/initdb.d:/docker-entrypoint-initdb.d
      - ./challenges/web01/db/conf.d:/etc/mysql/conf.d
    networks:
      web01:

  web02:
    build: ./challenges/web02/web/
    restart: always
    ports:
      - "10002:80"
    volumes:
      - ./challenges/web02/web/pages:/var/www/html
    depends_on:
      - web02-db
    networks:
      default:
      web02: 

  web02-db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=sample_db
    volumes:
      - ./challenges/web02/db/initdb.d:/docker-entrypoint-initdb.d
      - ./challenges/web02/db/conf.d:/etc/mysql/conf.d
    networks:
      web02:


networks:
    default:
    web01:
        internal: true
    web02:
        internal: true
    internal:
        internal: true
